/**
 * queue names
 */
const QUEUE_NAME_SEND_MAIL_EVENT = 'SendMailEvent';
const QUEUE_NAME_SEND_MAIL_DEATH_ANNIVERSARY = 'SendMailDeathAnniversary';
/**
 * job names
 */

const JOB_NAME_SEND_MAIL_TEMPLE_CREATE_EVENT = 'SendMailTempleCreateEvent';
const JOB_NAME_SEND_MAIL_TEMPLE_UPDATE_EVENT = 'SendMailTempleUpdateEvent';
const JOB_NAME_SEND_MAIL_TEMPLE_CANCEL_EVENT = 'SendMailTempleCancelEvent';
const JOB_NAME_SEND_MAIL_REQUEST_DEATH_ANNIVERSARY =
  'SendMailRequestDeathAnniversary';

export const QUEUE_MODULE_OPTIONS = {
  SEND_MAIL_EVENT: {
    NAME: QUEUE_NAME_SEND_MAIL_EVENT as TQueueName,
    JOBS: {
      SEND_CREATE_EVENT_MAIL:
        JOB_NAME_SEND_MAIL_TEMPLE_CREATE_EVENT as TJobName,
      SEND_UPDATE_EVENT_MAIL:
        JOB_NAME_SEND_MAIL_TEMPLE_UPDATE_EVENT as TJobName,
      SEND_CANCEL_EVENT_MAIL:
        JOB_NAME_SEND_MAIL_TEMPLE_CANCEL_EVENT as TJobName,
    },
  },
  SEND_MAIL_DEATH_ANNIVERSARY: {
    NAME: QUEUE_NAME_SEND_MAIL_DEATH_ANNIVERSARY as TQueueName,
    JOBS: {
      SEND_REQUEST_DEATH_ANNIVERSARY:
        JOB_NAME_SEND_MAIL_REQUEST_DEATH_ANNIVERSARY as TJobName,
    },
  },
};

/**
 * type queue name
 */
export type TQueueName =
  | typeof QUEUE_NAME_SEND_MAIL_EVENT
  | typeof QUEUE_NAME_SEND_MAIL_DEATH_ANNIVERSARY;

/**
 * type job name
 */
export type TJobName =
  | typeof JOB_NAME_SEND_MAIL_TEMPLE_CREATE_EVENT
  | typeof JOB_NAME_SEND_MAIL_TEMPLE_UPDATE_EVENT
  | typeof JOB_NAME_SEND_MAIL_TEMPLE_CANCEL_EVENT
  | typeof JOB_NAME_SEND_MAIL_REQUEST_DEATH_ANNIVERSARY;
