export enum EEnvironment {
  DEVELOPMENT = 'DEVELOPMENT',
  STAGING = 'STAGING',
  PRODUCTION = 'PRODUCTION',
}

export enum ERole {
  SYSTEM = 'SYSTEM',
  FAMILY_ADMIN = 'FAMILY_ADMIN',
  FAMILY_MEMBER = 'FAMILY_MEMBER',
  TEMPLE_ADMIN = 'TEMPLE_ADMIN',
  TEMPLE_MEMBER = 'TEMPLE_MEMBER',
  PUBLIC_USER = 'PUBLIC_USER',
}

export enum EGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum EAppLanguage {
  vi = 'vi',
  ja = 'ja',
  en = 'en',
}

export enum EStatus {
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  BLOCKED = 'BLOCKED',
}

export enum EDeathAnniversaryType {
  FIRST_ANNIVERSARY = 'FIRST_ANNIVERSARY',
  SECOND_ANNIVERSARY = 'SECOND_ANNIVERSARY',
  REGULAR_ANNIVERSARY = 'REGULAR_ANNIVERSARY',
}

export enum EDeathAnniversaryStatus {
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  READY = 'READY',
  CANCEL = 'CANCEL',
  FINISHED = 'FINISHED',
}

export enum EPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum EPlan {
  FREE = 'FREE',
  PREMIUM = 'PREMIUM',
}

export enum EBookingStatus {
  BOOKING = 'BOOKING',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  CANCEL = 'CANCEL',
}

export enum ESortOrder {
  ASC = 'ASC',
  DESC = 'DESC',
}

export enum ENotificationType {
  INVITE_FAMILY = 'INVITE_FAMILY',
  NEW_EVENT = 'NEW_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  CANCEL_EVENT = 'CANCEL_EVENT',
  APPROVE_EVENT_PARTICIPANT = 'APPROVE_EVENT_PARTICIPANT',
  REJECT_EVENT_PARTICIPANT = 'REJECT_EVENT_PARTICIPANT',
  REQUEST_DEATH_ANNIVERSARY = 'REQUEST_DEATH_ANNIVERSARY',
}

export enum EMailType {
  APPROVE_EVENT_PARTICIPANT = 'APPROVE_EVENT_PARTICIPANT',
  REJECT_EVENT_PARTICIPANT = 'REJECT_EVENT_PARTICIPANT',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  REGISTER = 'REGISTER',
  RESET_PASSWORD = 'RESET_PASSWORD',
  CREATE_EVENT = 'CREATE_EVENT',
  UPDATE_EVENT = 'UPDATE_EVENT',
  CANCEL_EVENT = 'CANCEL_EVENT',
  REQUEST_DEATH_ANNIVERSARY = 'REQUEST_DEATH_ANNIVERSARY',
}

export enum EValidationTokenType {
  RESET_PASSWORD = 'RESET_PASSWORD',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
}

export enum EAccountStatus {
  INACTIVE = 'INACTIVE',
  ACTIVE = 'ACTIVE',
}
