export enum ErrorMessage {
  ACCOUNT_NOT_EXISTS = 'error.ACCOUNT_NOT_EXISTS',
  ACCOUNT_EXISTS = 'error.ACCOUNT_EXISTS',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
  REFRESH_TOKEN_NOT_EXISTS = 'error.REFRESH_TOKEN_NOT_EXISTS',
  UNAUTHORIZED = 'error.UNAUTHORIZED',
  INVALID_PARAM = 'error.INVALID_PARAM',
  FAMILY_NOT_IN_TEMPLE = 'error.FAMILY_NOT_IN_TEMPLE',
  DECEASED_NOT_IN_FAMILY = 'error.DECEASED_NOT_IN_FAMILY',
  TEMPLE_NOT_EXIST = 'error.TEMPLE_NOT_EXIST',
}
